#!/bin/bash
#$ -cwd
#SBATCH --job-name multipole_ORCA
#SBATCH --account OPEN-33-34
#SBATCH --partition qcpu
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 128
#SBATCH --time 00:48:00

ORCADIR=/mnt/proj1/open-33-34/ORCA/1_ORCA_molmps_devel/x86_exe

ml imkl
ml GCC
ml OpenMPI

THISDIR=$PWD
TMPDIR=/scratch/project/open-31-30/orca_$SLURM_JOB_ID
mkdir -p $TMPDIR
cd $TMPDIR

JOB_NAME=$SLURM_JOB_NAME
mkdir -p $TMPDIR
cd $TMPDIR
export PATH=$ORCADIR:$PATH
#cp $THISDIR/dmrg.input .
cp $THISDIR/inputOrbs.gbw .

#export MOLMPS_NUM_THREADS=$PBS_NCPUS 
export MOLMPS_NUM_THREADS=128 
#export LD_LIBRARY_PATH=/home/jirka/ompi_1.6.5/lib:/opt/intel/composer_xe_2013_sp1/mkl/lib/intel64:$ORCADIR/../otool_molmps:$LD_LIBRARY_PATH

cat << Eof > $JOB_NAME.inp
!CCSD 6-311G*  
%MaxCore 40000

#%pal
#nprocs 16 
#end

%elprop 
	Dipole        true # dipole moment
        Quadrupole    true # quadrupole moment
end

%coords
  Ctyp xyz
  Charge 1
  Mult 1
  Units Angs
coords

C                 -0.80658313    1.22973465    0.03041801
C                  0.56153576    1.23725234    0.01622618
C                  1.22915389    0.01001055    0.01220575
H                 -1.36676923    2.15803094    0.04420367
H                  1.14116413    2.14927050    0.01037697
N                  2.71357475    0.03144573   -0.00289824
O                  3.28013247   -1.09741954   -0.00254733
O                  3.24714953    1.17621948   -0.01252002
C                 -0.77042978   -1.26805414    0.04039660
H                 -1.30353926   -2.21202933    0.06122375
C                  0.59726287   -1.23605918    0.02634378
H                  1.20308359   -2.13089607    0.02793117
C                 -1.56287141   -0.03049318    0.01040538
H                 -2.41148563   -0.03994459    0.70143946
Br                -2.40993182   -0.04931830   -1.82359612

end
end
Eof


$ORCADIR/orca $JOB_NAME.inp > $THISDIR/$JOB_NAME.out

orca_2mkl $JOB_NAME -molden 

mv $TMPDIR $THISDIR
