#!/bin/bash
#$ -cwd
#SBATCH --job-name QED-CI_test
#SBATCH --account OPEN-34-25
#SBATCH --partition qcpu
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 128
#SBATCH --time 00:48:00

. /home/matoumik/.bashrc

export PYTHONPATH=/home/matoumik/build/qed-ci/src:$PYTHONPATH

ml intel
ml Anaconda3
#conda init
conda activate psi4env


THISDIR=$PWD
TMPDIR=/scratch/project/open-31-30/psi4_$SLURM_JOB_ID
mkdir -p $TMPDIR
cd $TMPDIR

export PSI_SCRATCH=$TMPDIR

export MKL_NUM_THREADS=$SLURM_NTASKS_PER_NODE
export OMP_NUM_THREADS=$SLURM_NTASKS_PER_NODE

cat << Eof > $SLURM_JOB_NAME.inp
import psi4
from helper_PFCI import PFHamiltonianGenerator
import numpy as np
from FCIDUMP_writer import make_permutation
mol_str = """
0 1
symmetry c1
 C    -1.820563    1.210103    0.000142
 C    -0.429516    1.217922    0.000173
 C     0.242206    0.000000    0.000184
 H    -2.361810    2.149763   -0.000162
 H     0.136838    2.139364    0.000104
 N     1.722746   -0.000000    0.000106
 O     2.289251   -1.084455   -0.000114
 O     2.289251    1.084454   -0.000213
 C    -1.820564   -1.210103    0.000100
 H    -2.361812   -2.149762   -0.000242
 C    -0.429517   -1.217922    0.000137
 H     0.136837   -2.139364    0.000049
 C    -2.514942    0.000000   -0.000199
 H    -3.599911   -0.000000   -0.001087
"""

options_dict = {
        "basis": "6-311G*",
        "scf_type": "pk",
        "e_convergence": 1e-10,
        "d_convergence": 1e-10,
}

cavity_dict = {
        'omega_value' : 0.06615, 
        'lambda_vector' : np.array([0.383022,0.821394,0.422618])*0.1, 
        'ci_level' : 'fcidump',
        'davidson_roots' : 10,
        'number_of_photons' : 10,
        'photon_number_basis' : True,
        'canonical_mos' : True,
        'coherent_state_basis' : False,
	'nact_orbs' : 9,
	'nact_els' : 10,
        "manual_ordering" : make_permutation([20,26,30,31,32,33,34,36,42],32,177),   
	'localize_active_full':True,
   #     "localize_active" : True,
}

psi4.set_num_threads($SLURM_NTASKS_PER_NODE);

test_pf = PFHamiltonianGenerator(
        mol_str,
        options_dict,
        cavity_dict
)


Eof

python3 $SLURM_JOB_NAME.inp >> $THISDIR/$SLURM_JOB_NAME.out




cp -r $TMPDIR $THISDIR
cp $TMPDIR/FCIDUMP* $THISDIR
rm -r $TMPDIR



